version: '3'

services:
    api:
        # platform: linux/amd64
        image: chartgpt-api
        build:
            dockerfile: ./api/Dockerfile
            context: .
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - PORT=8080
    discord-bot:
        image: chartgpt-discord-bot
        build:
            dockerfile: ./bots/discord/Dockerfile
            context: .
    slack-bot:
        image: chartgpt-slack-bot
        build:
            dockerfile: ./bots/slack/Dockerfile
            context: .
    telegram-bot:
        image: chartgpt-telegram-bot
        build:
            dockerfile: ./bots/telegram/Dockerfile
            context: .
